In [ ]:
#importing the pandas package

import pandas as pd

In [ ]:
#creating a pandas Series from a list

moja_lista=[1,2,4,5,6,7,8,9]
data= pd.Series(moja_lista)
print(data)

0    1
1    2
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int64

In [ ]:
#creating a Series from a list with indexes

indexed_data = pd.Series([10,20,30,40,50], index=['mon','tue','wed','thu','fri'])
print(indexed_data)

mon    10
tue    20
wed    30
thu    40
fri    50
dtype: int64

In [ ]:
#example: indexes help count values regardless of their order

a = pd.Series([1,2], index=["x","y"])
b= pd.Series([6,4], index =["y","x"])
a+b

x    5
y    8
dtype: int64

In [ ]:
#creating a pandas DataFrame from a list of dictionaries

data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charles', 'Age': 35, 'City': 'Chicago'}
]
df2= pd.DataFrame(data)
df2

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charles   35      Chicago

In [ ]:
#creating/loading a DataFrame from a .csv file – head (number of top rows), tail (number of bottom rows)

df_test= pd.read_csv('/content/sample_data/california_housing_test.csv')
df_test.tail(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
#creating a DataFrame from an Excel file, specifying the sheet name, skiprows – skipping rows, usecols – selecting specific columns

df_netflix= pd.read_excel(
    '/content/sample_data/netflix_titles.xlsx',
    sheet_name='netflix_titles'
    #skiprows=0,
    #usecols='A:E'
    )
df_netflix.head(11)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
0,90.0,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0
1,94.0,NaN,Movie,Jandino: Whatever it Takes,2016-09-09,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0
2,NaN,1.0,TV Show,Transformers Prime,2018-09-08,2013.0,TV-Y7-FV,"With the help of three human allies, the Autob...",70234439.0
3,NaN,1.0,TV Show,Transformers: Robots in Disguise,2018-09-08,2016.0,TV-Y7,When a prison ship crash unleashes hundreds of...,80058654.0
4,99.0,NaN,Movie,#realityhigh,2017-09-08,2017.0,TV-14,When nerdy high schooler Dani finally attracts...,80125979.0
5,NaN,1.0,TV Show,Apaches,2017-09-08,2016.0,TV-MA,A young journalist is forced into a life of cr...,80163890.0
6,110.0,NaN,Movie,Automata,2017-09-08,2014.0,R,"In a dystopian future, an insurance adjuster f...",70304989.0
7,60.0,NaN,Movie,Fabrizio Copano: Solo pienso en mi,2017-09-08,2017.0,TV-MA,Fabrizio Copano takes audience participation t...,80164077.0
8,NaN,1.0,TV Show,Fire Chasers,2017-09-08,2017.0,TV-MA,"As California's 2016 fire season rages, brave ...",80117902.0
9,90.0,NaN,Movie,Good People,2017-09-08,2014.0,R,A struggling couple can't believe their luck w...,70304990.0
10,78.0,NaN,Movie,Joaquín Reyes: Una y no más,2017-09-08,2017.0,TV-MA,Comedian and celebrity impersonator Joaquín Re...,80169755.0

In [ ]:
#basic data information

df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6235 entries, 0 to 6234
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   duration_minutes  4265 non-null   float64
 1   duration_seasons  1969 non-null   float64
 2   type              6234 non-null   object
 3   title             6229 non-null   object
 4   date_added        6222 non-null   datetime64[ns]
 5   release_year      6233 non-null   float64
 6   rating            6223 non-null   object
 7   description       6233 non-null   object
 8   show_id           6232 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 438.5+ KB

In [ ]:
#basic statistics from the data

df_netflix.describe()

,duration_minutes,duration_seasons,date_added,release_year,show_id
count,4265.000000,1969.000000,6222,6233.000000,6.232000e+03
mean,99.100821,1.779584,2018-07-01 17:22:37.377049088,2013.370448,7.670257e+07
min,3.000000,1.000000,2008-01-01 00:00:00,1925.000000,2.477470e+05
25%,86.000000,1.000000,2017-10-01 00:00:00,2013.000000,8.003569e+07
50%,98.000000,1.000000,2018-09-30 00:00:00,2016.000000,8.016337e+07
75%,115.000000,2.000000,2019-06-08 00:00:00,2018.000000,8.024491e+07
max,312.000000,15.000000,2020-01-18 00:00:00,2020.000000,8.123573e+07
std,28.074857,1.624936,NaN,8.768412,1.094455e+07

In [ ]:
#selecting a single column from a DataFrame

df_netflix['title']

0           Norm of the North: King Sized Adventure
1                        Jandino: Whatever it Takes
2                                Transformers Prime
3                  Transformers: Robots in Disguise
4                                      #realityhigh
                           ...
6230                                   Red vs. Blue
6231                                          Maron
6232         Little Baby Bum: Nursery Rhyme Friends
6233    A Young Doctor's Notebook and Other Stories
6234                                        Friends
Name: title, Length: 6235, dtype: object

In [ ]:
#selecting specific rows from a DataFrame using iloc

selected_row= df_netflix.iloc[[1,4,6,7,8]]
selected_row

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
1,94.0,NaN,Movie,Jandino: Whatever it Takes,2016-09-09,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0
4,99.0,NaN,Movie,#realityhigh,2017-09-08,2017.0,TV-14,When nerdy high schooler Dani finally attracts...,80125979.0
6,110.0,NaN,Movie,Automata,2017-09-08,2014.0,R,"In a dystopian future, an insurance adjuster f...",70304989.0
7,60.0,NaN,Movie,Fabrizio Copano: Solo pienso en mi,2017-09-08,2017.0,TV-MA,Fabrizio Copano takes audience participation t...,80164077.0
8,NaN,1.0,TV Show,Fire Chasers,2017-09-08,2017.0,TV-MA,"As California's 2016 fire season rages, brave ...",80117902.0

In [ ]:
#selecting specific rows and columns from a DataFrame using iloc

selected_rc=df_netflix.iloc[[5,4],[4,6]]
selected_rc

  date_added rating
5 2017-09-08  TV-MA
4 2017-09-08  TV-14

In [ ]:
#selecting rows based on a condition

year_over2015= df_netflix[df_netflix['release_year'] > 2015]
year_over2015

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
0,90.0,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0
1,94.0,NaN,Movie,Jandino: Whatever it Takes,2016-09-09,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0
3,NaN,1.0,TV Show,Transformers: Robots in Disguise,2018-09-08,2016.0,TV-Y7,When a prison ship crash unleashes hundreds of...,80058654.0
4,99.0,NaN,Movie,#realityhigh,2017-09-08,2017.0,TV-14,When nerdy high schooler Dani finally attracts...,80125979.0
5,NaN,1.0,TV Show,Apaches,2017-09-08,2016.0,TV-MA,A young journalist is forced into a life of cr...,80163890.0
...,...,...,...,...,...,...,...,...,...
6220,NaN,2.0,TV Show,Pokémon the Series,2019-04-01,2019.0,TV-Y7-FV,Ash and his Pikachu travel to the Alola region...,80186475.0
6222,NaN,2.0,TV Show,Terrace House: Boys & Girls in the City,2016-04-01,2016.0,TV-14,A new set of six men and women start their liv...,80067942.0
6225,NaN,5.0,TV Show,Anthony Bourdain: Parts Unknown,NaT,2018.0,TV-PG,This CNN original series has chef Anthony Bour...,70304979.0
6231,NaN,4.0,TV Show,Maron,NaT,2016.0,TV-MA,"Marc Maron stars as Marc Maron, who interviews...",70286564.0
6232,60.0,NaN,Movie,Little Baby Bum: Nursery Rhyme Friends,NaT,2016.0,NaN,Nursery rhymes and original music for children...,80116008.0

In [ ]:
#sorting by a column; ascending=False sorts in descending order

posortowane_dane = df_netflix.sort_values(by='release_year', ascending=False)
posortowane_dane

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
3464,NaN,1.0,TV Show,AJ and the Queen,2020-01-10,2020.0,TV-14,While traveling across the country in a run-do...,80237329.0
3354,NaN,1.0,TV Show,Nailed It! Germany,2020-01-17,2020.0,TV-14,Home cooks try – and inevitably fail – to re-c...,81062580.0
3220,NaN,1.0,TV Show,Dracula,2020-01-04,2020.0,TV-14,The Count Dracula legend transforms with new t...,80997687.0
3363,NaN,1.0,TV Show,Handsome Siblings,2020-01-16,2020.0,TV-14,Clashing martial arts twins face relentless vi...,80996973.0
3353,NaN,1.0,TV Show,Ares,2020-01-17,2020.0,TV-MA,"Aiming to become part of Amsterdam's elite, an...",80995039.0
...,...,...,...,...,...,...,...,...,...
2013,18.0,NaN,Movie,The Battle of Midway,2017-03-31,1942.0,TV-G,Director John Ford captures combat footage of ...,60027942.0
2011,52.0,NaN,Movie,Prelude to War,2017-03-31,1942.0,TV-PG,Frank Capra's documentary chronicles the rise ...,60027945.0
4292,NaN,1.0,TV Show,Pioneers: First Women Filmmakers*,2018-12-30,1925.0,TV-PG,This collection restores films from women who ...,81030762.0
2017,40.0,NaN,Movie,The Memphis Belle: A Story of a,NaT,NaN,NaN,NaN,NaN
4524,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [ ]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charles', 'Age': 35, 'City': 'Chicago'}
]
df2= pd.DataFrame(data)
df2

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charles   35      Chicago

In [ ]:
#creating a new column with different values per row

df2['Country']=["PL","DE","FR"]
df2

      Name  Age         City Country
0    Alice   25     New York      PL
1      Bob   30  Los Angeles      DE
2  Charles   35      Chicago      FR

In [ ]:
#creating a column with a constant value

df2['Day of the week']=5
df2

      Name  Age         City Country  Day of the week
0    Alice   25     New York      PL                5
1      Bob   30  Los Angeles      DE                5
2  Charles   35      Chicago      FR                5

In [ ]:
#removing a column

df2.drop(columns='Country', inplace=True)
df2

      Name  Age         City  Day of the week
0    Alice   25     New York                5
1      Bob   30  Los Angeles                5
2  Charles   35      Chicago                5

In [ ]:
df_netflix

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
0,90.0,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0
1,94.0,NaN,Movie,Jandino: Whatever it Takes,2016-09-09,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0
2,NaN,1.0,TV Show,Transformers Prime,2018-09-08,2013.0,TV-Y7-FV,"With the help of three human allies, the Autob...",70234439.0
3,NaN,1.0,TV Show,Transformers: Robots in Disguise,2018-09-08,2016.0,TV-Y7,When a prison ship crash unleashes hundreds of...,80058654.0
4,99.0,NaN,Movie,#realityhigh,2017-09-08,2017.0,TV-14,When nerdy high schooler Dani finally attracts...,80125979.0
...,...,...,...,...,...,...,...,...,...
6230,NaN,13.0,TV Show,Red vs. Blue,NaT,2015.0,NR,"This parody of first-person shooter games, mil...",80000063.0
6231,NaN,4.0,TV Show,Maron,NaT,2016.0,TV-MA,"Marc Maron stars as Marc Maron, who interviews...",70286564.0
6232,60.0,NaN,Movie,Little Baby Bum: Nursery Rhyme Friends,NaT,2016.0,NaN,Nursery rhymes and original music for children...,80116008.0
6233,NaN,2.0,TV Show,A Young Doctor's Notebook and Other Stories,NaT,2013.0,TV-MA,"Set during the Russian Revolution, this comic ...",70281022.0
6234,NaN,10.0,TV Show,Friends,NaT,2003.0,TV-14,This hit sitcom follows the merry misadventure...,70153404.0

In [ ]:
#counting rows by a specific category

df_netflix['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

In [ ]:
#nunique – counting unique values in a column

df_netflix['rating'].nunique()
df_netflix['rating'].value_counts()

rating
TV-MA       2027
TV-14       1698
TV-PG        700
R            508
PG-13        286
NR           218
PG           184
TV-Y7        169
TV-G         149
TV-Y         143
TV-Y7-FV      95
G             37
UR             7
NC-17          2
Name: count, dtype: int64

In [ ]:
#aggregation – sum

total_sum=df_netflix[['duration_minutes','duration_seasons']].sum()
total_sum

duration_minutes    422665.0
duration_seasons      3504.0
dtype: float64

In [ ]:
#aggregation – mean

table_mean=df_netflix[['duration_minutes','duration_seasons']].mean()
table_mean

duration_minutes    99.100821
duration_seasons     1.779584
dtype: float64

In [ ]:
#aggregation – median; you can also use: min, max, std

table_median=df_netflix[['duration_minutes','duration_seasons']].median()
table_median

duration_minutes    98.0
duration_seasons     1.0
dtype: float64

In [ ]:
#aggregation: two columns, multiple calculations

df_netflix.groupby('type')[['duration_minutes','duration_seasons']].agg(['min','max','mean','median'])

        duration_minutes                          duration_seasons        \
                     min    max       mean median              min   max
type
Movie                3.0  312.0  99.100821   98.0              NaN   NaN
TV Show              NaN    NaN        NaN    NaN              1.0  15.0


             mean median
type
Movie         NaN    NaN
TV Show  1.779584    1.0

In [ ]:
#correlation matrix #1

correlation= df_netflix[['duration_minutes','duration_seasons']].corr()
correlation

                  duration_minutes  duration_seasons
duration_minutes               1.0               NaN
duration_seasons               NaN               1.0

In [ ]:
df_test= pd.read_csv('/content/sample_data/california_housing_test.csv')
df_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
#correlation matrix #2

corr_matrix= df_test[['median_income','median_house_value','housing_median_age','population']].corr()
corr_matrix

,median_income,median_house_value,housing_median_age,population
median_income,1.000000,0.672695,-0.144315,0.032361
median_house_value,0.672695,1.000000,0.091409,-0.001192
housing_median_age,-0.144315,0.091409,1.000000,-0.299888
population,0.032361,-0.001192,-0.299888,1.000000

In [ ]:
#aggregation – standard deviation

table_std=df_test[['median_income','population']].std()
table_std

median_income       1.854512
population       1030.543012
dtype: float64