In [ ]:
import pandas as pd

In [ ]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charles', 'Age': 35, 'City': 'Chicago'}
]
df1= pd.DataFrame(data)
df1

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charles   35      Chicago

In [ ]:
# adding a new column with predefined values

df1['Salary']= [1000,20000,50000]
df1

      Name  Age         City  Salary
0    Alice   25     New York    1000
1      Bob   30  Los Angeles   20000
2  Charles   35      Chicago   50000

In [ ]:
# adding a new column, basic mathematical operations


df1['Salary_taxed']=df1['Salary']*1.4
df1

      Name  Age         City  Salary  Salary_taxed
0    Alice   25     New York    1000        1400.0
1      Bob   30  Los Angeles   20000       28000.0
2  Charles   35      Chicago   50000       70000.0

In [ ]:
df1['Tax']=df1['Salary_taxed']-df1['Salary']
df1

      Name  Age         City  Salary  Salary_taxed      Tax
0    Alice   25     New York    1000        1400.0    400.0
1      Bob   30  Los Angeles   20000       28000.0   8000.0
2  Charles   35      Chicago   50000       70000.0  20000.0

In [ ]:
# removing a column


df1=df1.drop(['Age'], axis=1)
df1

In [ ]:
# removing rows



df1=df1.drop([1,2], axis=0)
df1

    Name  Age      City  Salary  Salary_taxed    Tax
0  Alice   25  New York    1000        1400.0  400.0

In [ ]:
df_tst = pd.read_csv('/content/sample_data/california_housing_test.csv')
df_tst.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
# filtering – can replace row removal if we create a new DataFrame


df_tst2=df_tst[df_tst['housing_median_age'] >= 30]
df_tst2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0
10,-118.24,33.98,45.0,972.0,249.0,1288.0,261.0,2.2054,125000.0
...,...,...,...,...,...,...,...,...,...
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2994,-117.93,33.86,35.0,931.0,181.0,516.0,174.0,5.5867,182500.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# filtering by multiple conditions


df_tst3=df_tst.loc[
    (df_tst['housing_median_age'] >= 30) &
    (df_tst['households']>=500)
]
df_tst3.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0
19,-122.59,38.01,35.0,8814.0,1307.0,3450.0,1258.0,6.1724,414300.0
22,-118.16,34.07,47.0,2994.0,543.0,1651.0,561.0,3.8644,241500.0
26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
29,-118.48,34.01,30.0,3078.0,954.0,1561.0,901.0,3.4852,425000.0
31,-118.30,33.91,34.0,1617.0,493.0,1530.0,500.0,2.6182,172600.0
35,-118.11,34.00,33.0,2886.0,726.0,2650.0,728.0,2.6250,178700.0
65,-117.22,32.73,38.0,3966.0,768.0,1640.0,729.0,3.8409,291400.0
71,-118.20,34.04,44.0,1582.0,544.0,1998.0,515.0,1.6888,125000.0
76,-121.89,37.35,47.0,2879.0,631.0,2229.0,606.0,3.2599,183100.0

In [ ]:
df_tst.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [ ]:
# removing multiple rows by index


df_tst4=df_tst.drop(df_tst.loc[1:10].index)
df_tst4

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
12,-121.93,37.25,36.0,1089.0,182.0,535.0,170.0,4.6900,252600.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
14,-117.97,33.73,27.0,2097.0,325.0,1217.0,331.0,5.7121,222500.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# displaying data types in the DataFrame


df_tst4.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
# displaying the data type of a single column


df_tst4['latitude'].dtypes

dtype('float64')

In [ ]:
# changing data types


df_tst4['latitude'].astype('int')

0       37
11      35
12      37
13      32
14      33
        ..
2995    34
2996    34
2997    36
2998    34
2999    34
Name: latitude, Length: 2990, dtype: int64

In [ ]:
# renaming a column


df_tst5=df_tst4.rename(columns={'latitude':'lat.'})
df_tst5

,longitude,lat.,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
12,-121.93,37.25,36.0,1089.0,182.0,535.0,170.0,4.6900,252600.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
14,-117.97,33.73,27.0,2097.0,325.0,1217.0,331.0,5.7121,222500.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df6 = pd.DataFrame({
    'Name': ['Alice', 'Bob', None, 'David'],
    'Age': [25, 30, 35, None]
})
df6

    Name   Age
0  Alice  25.0
1    Bob  30.0
2   None  35.0
3  David   NaN

In [ ]:
# matrix showing True values for nulls


df6.isnull()

    Name    Age
0  False  False
1  False  False
2   True  False
3  False   True

In [ ]:
# sum of null values per column


df6.isnull().sum()

Name    1
Age     1
dtype: int64

In [ ]:
# removing rows containing null values


df7=df6.dropna()
df7

    Name   Age
0  Alice  25.0
1    Bob  30.0

In [ ]:
# replacing missing values


df8=df6.fillna('Brak danych')
df8

          Name          Age
0        Alice         25.0
1          Bob         30.0
2  Brak danych         35.0
3        David  Brak danych

In [ ]:
df6.fillna('Brak danych', inplace=True)
df6

          Name          Age
0        Alice         25.0
1          Bob         30.0
2  Brak danych         35.0
3        David  Brak danych

In [ ]:
df6

          Name          Age
0        Alice         25.0
1          Bob         30.0
2  Brak danych         35.0
3        David  Brak danych

In [ ]:
df_abc = pd.DataFrame({
    'Name': ['Alice', 'Bob', None, 'David'],
    'Age': [25, 30, 35, None]
})
df_abc

    Name   Age
0  Alice  25.0
1    Bob  30.0
2   None  35.0
3  David   NaN

In [ ]:
# replacing missing numeric values with the mean


srednia=df_abc['Age'].mean()
df_abc['Age'].fillna(srednia, inplace=True)
df_abc

/tmp/ipython-input-2993995773.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_abc['Age'].fillna(srednia, inplace=True)

    Name   Age
0  Alice  25.0
1    Bob  30.0
2   None  35.0
3  David  30.0

In [ ]:
df_abc['Name'].fillna('no name', inplace=True)
df_abc

/tmp/ipython-input-1262573918.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_abc['Name'].fillna('no name', inplace=True)

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  no name  35.0
3    David  30.0

In [ ]:
kategorie = pd.DataFrame({
    'Name': ['Alice', 'Bob', None, 'David'],
    'Category': ['A', 'B', 'C', 'A']
})
kategorie

    Name Category
0  Alice        A
1    Bob        B
2   None        C
3  David        A

In [ ]:
# mapping categories


mapowanie={
    'A':'Premium',
    'B':'Medium',
    "C":'Economy'
}
kategorie['Upper_Level'] = kategorie['Category'].map(mapowanie)
kategorie

    Name Category Upper_Level
0  Alice        A     Premium
1    Bob        B      Medium
2   None        C     Economy
3  David        A     Premium

In [ ]:
# mapping using a function


def funkcja_mapujaca(kategorie):
  if kategorie['Category'] == 'A':
    return "Kategoria A"
  else:
    return "Kategoria B lub C"

kategorie['Highest_Level'] = kategorie.apply(funkcja_mapujaca, axis=1)
kategorie

    Name Category Upper_Level      Highest_Level
0  Alice        A     Premium        Kategoria A
1    Bob        B      Medium  Kategoria B lub C
2   None        C     Economy  Kategoria B lub C
3  David        A     Premium        Kategoria A

In [ ]:
zachowanie_klientow = pd.read_excel('/content/sample_data/User_Behavior_Data (1).xlsx')
profile_klientow = pd.read_excel('/content/sample_data/User_Profiles.xlsx')

In [ ]:
zachowanie_klientow.head(10)

,Date,UserID,Session_Duration,Pages_Viewed,Device,Purchases,Location,Referral_Source,Account_Age_Days
0,2021-01-01,U001,103.0,2.0,Mobile,4.0,France,Social Media,179.0
1,2021-01-02,U002,349.0,1.0,Mobile,1.0,France,Direct,63.0
2,2021-01-03,U003,271.0,12.0,Desktop,NaN,USA,Google,352.0
3,2021-01-04,U004,107.0,12.0,Mobile,3.0,USA,Other,231.0
4,2021-01-05,U005,72.0,17.0,Desktop,1.0,USA,Email,NaN
5,2021-01-06,U006,189.0,10.0,Mobile,NaN,USA,Social Media,52.0
6,2021-01-07,U007,21.0,NaN,Tablet,3.0,Germany,Email,96.0
7,2021-01-08,U008,NaN,15.0,Tablet,3.0,UK,Email,NaN
8,2021-01-09,U009,122.0,15.0,Desktop,0.0,UK,Google,231.0
9,2021-01-10,U010,215.0,19.0,Tablet,4.0,USA,Email,237.0

In [ ]:
profile_klientow.head(10)

,UserID,Age,Gender,Membership_Level,Email,Country,Subscription_Date
0,U001,56,Female,Gold,user001@example.com,Germany,2019-01-01
1,U002,46,Female,Bronze,user002@example.com,France,2019-01-16
2,U003,32,Female,Gold,user003@example.com,UK,2019-01-31
3,U004,60,Male,Bronze,user004@example.com,Australia,2019-02-15
4,U005,25,Male,Gold,user005@example.com,USA,2019-03-02
5,U006,38,Female,Gold,user006@example.com,Germany,2019-03-17
6,U007,56,Female,Bronze,user007@example.com,Canada,2019-04-01
7,U008,36,Male,Bronze,user008@example.com,Germany,2019-04-16
8,U009,40,Male,Gold,user009@example.com,Canada,2019-05-01
9,U010,28,Male,Silver,user010@example.com,Australia,2019-05-16

In [ ]:
#merge (inner)

polaczone_dane = pd.merge(zachowanie_klientow,profile_klientow, on='UserID')
polaczone_dane.head(5)

,Date,UserID,Session_Duration,Pages_Viewed,Device,Purchases,Location,Referral_Source,Account_Age_Days,Age,Gender,Membership_Level,Email,Country,Subscription_Date
0,2021-01-01,U001,103.0,2.0,Mobile,4.0,France,Social Media,179.0,56,Female,Gold,user001@example.com,Germany,2019-01-01
1,2021-01-02,U002,349.0,1.0,Mobile,1.0,France,Direct,63.0,46,Female,Bronze,user002@example.com,France,2019-01-16
2,2021-01-03,U003,271.0,12.0,Desktop,NaN,USA,Google,352.0,32,Female,Gold,user003@example.com,UK,2019-01-31
3,2021-01-04,U004,107.0,12.0,Mobile,3.0,USA,Other,231.0,60,Male,Bronze,user004@example.com,Australia,2019-02-15
4,2021-01-05,U005,72.0,17.0,Desktop,1.0,USA,Email,NaN,25,Male,Gold,user005@example.com,USA,2019-03-02

In [ ]:
#merge (left)

polaczone_dane_left = pd.merge(zachowanie_klientow,profile_klientow, on='UserID', how='left')
polaczone_dane_left.head(5)

,Date,UserID,Session_Duration,Pages_Viewed,Device,Purchases,Location,Referral_Source,Account_Age_Days,Age,Gender,Membership_Level,Email,Country,Subscription_Date
0,2021-01-01,U001,103.0,2.0,Mobile,4.0,France,Social Media,179.0,56,Female,Gold,user001@example.com,Germany,2019-01-01
1,2021-01-02,U002,349.0,1.0,Mobile,1.0,France,Direct,63.0,46,Female,Bronze,user002@example.com,France,2019-01-16
2,2021-01-03,U003,271.0,12.0,Desktop,NaN,USA,Google,352.0,32,Female,Gold,user003@example.com,UK,2019-01-31
3,2021-01-04,U004,107.0,12.0,Mobile,3.0,USA,Other,231.0,60,Male,Bronze,user004@example.com,Australia,2019-02-15
4,2021-01-05,U005,72.0,17.0,Desktop,1.0,USA,Email,NaN,25,Male,Gold,user005@example.com,USA,2019-03-02

In [ ]:
#join

zbior_joined = zachowanie_klientow.join(profile_klientow, lsuffix='_zachowania', rsuffix='_klientow' )
zbior_joined.head(5)

,Date,UserID_zachowania,Session_Duration,Pages_Viewed,Device,Purchases,Location,Referral_Source,Account_Age_Days,UserID_klientow,Age,Gender,Membership_Level,Email,Country,Subscription_Date
0,2021-01-01,U001,103.0,2.0,Mobile,4.0,France,Social Media,179.0,U001,56,Female,Gold,user001@example.com,Germany,2019-01-01
1,2021-01-02,U002,349.0,1.0,Mobile,1.0,France,Direct,63.0,U002,46,Female,Bronze,user002@example.com,France,2019-01-16
2,2021-01-03,U003,271.0,12.0,Desktop,NaN,USA,Google,352.0,U003,32,Female,Gold,user003@example.com,UK,2019-01-31
3,2021-01-04,U004,107.0,12.0,Mobile,3.0,USA,Other,231.0,U004,60,Male,Bronze,user004@example.com,Australia,2019-02-15
4,2021-01-05,U005,72.0,17.0,Desktop,1.0,USA,Email,NaN,U005,25,Male,Gold,user005@example.com,USA,2019-03-02

In [ ]:
# setting an index from a column


zachowanie_klientow.set_index('UserID', inplace=True)
zachowanie_klientow.head(5)

,Date,Session_Duration,Pages_Viewed,Device,Purchases,Location,Referral_Source,Account_Age_Days
UserID,,,,,,,,
U001,2021-01-01,103.0,2.0,Mobile,4.0,France,Social Media,179.0
U002,2021-01-02,349.0,1.0,Mobile,1.0,France,Direct,63.0
U003,2021-01-03,271.0,12.0,Desktop,NaN,USA,Google,352.0
U004,2021-01-04,107.0,12.0,Mobile,3.0,USA,Other,231.0
U005,2021-01-05,72.0,17.0,Desktop,1.0,USA,Email,NaN

In [ ]:
# resetting the index


zachowanie_klientow.reset_index(inplace=True)
zachowanie_klientow

,UserID,Date,Session_Duration,Pages_Viewed,Device,Purchases,Location,Referral_Source,Account_Age_Days
0,U001,2021-01-01,103.0,2.0,Mobile,4.0,France,Social Media,179.0
1,U002,2021-01-02,349.0,1.0,Mobile,1.0,France,Direct,63.0
2,U003,2021-01-03,271.0,12.0,Desktop,NaN,USA,Google,352.0
3,U004,2021-01-04,107.0,12.0,Mobile,3.0,USA,Other,231.0
4,U005,2021-01-05,72.0,17.0,Desktop,1.0,USA,Email,NaN
5,U006,2021-01-06,189.0,10.0,Mobile,NaN,USA,Social Media,52.0
6,U007,2021-01-07,21.0,NaN,Tablet,3.0,Germany,Email,96.0
7,U008,2021-01-08,NaN,15.0,Tablet,3.0,UK,Email,NaN
8,U009,2021-01-09,122.0,15.0,Desktop,0.0,UK,Google,231.0
9,U010,2021-01-10,215.0,19.0,Tablet,4.0,USA,Email,237.0
10,U011,2021-01-11,331.0,12.0,Tablet,4.0,UK,Other,143.0
11,U012,2021-01-12,NaN,3.0,Mobile,1.0,UK,Email,NaN
12,U013,2021-01-13,100.0,5.0,Desktop,4.0,USA,Google,29.0
13,U014,2021-01-14,152.0,NaN,Mobile,1.0,UK,Other,36.0
14,U015,2021-01-15,NaN,7.0,Mobile,0.0,France,Direct,13.0
15,U016,2021-01-16,150.0,9.0,Mobile,NaN,Canada,Email,160.0
16,U017,2021-01-17,309.0,7.0,Mobile,3.0,Canada,Google,NaN
17,U018,2021-01-18,258.0,NaN,Mobile,3.0,USA,Direct,187.0
18,U019,2021-01-19,344.0,4.0,Mobile,4.0,Germany,Direct,243.0
19,U020,2021-01-20,294.0,14.0,Mobile,0.0,USA,Social Media,86.0

In [ ]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charles', 'Age': 35, 'City': 'Chicago'}
]

In [ ]:
df6 = pd.DataFrame({
    'Name': ['Alice', 'Bob', None, 'David'],
    'Age': [25, 30, 35, None]
})

In [ ]:
kategorie = pd.DataFrame({
    'Name': ['Alice', 'Bob', None, 'David'],
    'Category': ['A', 'B', 'C', 'A']
})